app_launch_prefix = "uwsm app -- "
as_window = false
close_when_open = false
disable_click_to_close = false
force_keyboard_focus = false
hotreload_theme = false
locale = ""
monitor = ""
terminal_title_flag = ""
theme = "default"
timeout = 0
[activation_mode]
labels = "jkl;asdf"

[builtins.ai]
icon = "help-browser"
name = "ai"
placeholder = "AI"
show_sub_when_single = true
switcher_only = true
weight = 5
[[builtins.ai.anthropic.prompts]]
label = "General Assistant"
max_tokens = 1000
model = "claude-3-7-sonnet-20250219"
prompt = "You are a helpful general assistant. Keep your answers short and precise."
temperature = 1

[builtins.applications]
context_aware = true
hide_actions_with_empty_query = true
history = true
name = "applications"
placeholder = "Applications"
prioritize_new = true
refresh = true
show_generic = true
show_icon_when_single = true
show_sub_when_single = true
weight = 5
[builtins.applications.actions]
enabled = true
hide_category = false
hide_without_query = true

[builtins.bookmarks]
icon = "bookmark"
name = "bookmarks"
placeholder = "Bookmarks"
switcher_only = true
weight = 5
[[builtins.bookmarks.entries]]
keywords = ["walker", "github"]
label = "Walker"
url = "https://github.com/abenz1267/walker"

[builtins.calc]
icon = "accessories-calculator"
min_chars = 4
name = "calc"
placeholder = "Calculator"
require_number = true
weight = 5

[builtins.clipboard]
always_put_new_on_top = true
avoid_line_breaks = true
exec = "wl-copy"
image_height = 300
max_entries = 10
name = "clipboard"
placeholder = "Clipboard"
switcher_only = true
weight = 5

[builtins.commands]
icon = "utilities-terminal"
name = "commands"
placeholder = "Commands"
switcher_only = true
weight = 5

[builtins.custom_commands]
icon = "utilities-terminal"
name = "custom_commands"
placeholder = "Custom Commands"
weight = 5

[builtins.dmenu]
hidden = true
name = "dmenu"
placeholder = "Dmenu"
show_icon_when_single = true
switcher_only = true
weight = 5

[builtins.emojis]
exec = "wl-copy"
history = true
name = "emojis"
placeholder = "Emojis"
show_unqualified = false
switcher_only = true
typeahead = true
weight = 5

[builtins.finder]
concurrency = 8
fd_flags = "--ignore-vcs --type file"
icon = "file"
ignore_gitignore = true
name = "finder"
placeholder = "Finder"
preview_images = false
refresh = true
show_icon_when_single = true
switcher_only = true
use_fd = false
weight = 5

[builtins.runner]
eager_loading = true
generic_entry = false
history = true
icon = "utilities-terminal"
name = "runner"
placeholder = "Runner"
refresh = true
typeahead = true
use_fd = false
weight = 5

[builtins.ssh]
history = true
icon = "preferences-system-network"
name = "ssh"
placeholder = "SSH"
refresh = true
switcher_only = true
weight = 5

[builtins.switcher]
name = "switcher"
placeholder = "Switcher"
prefix = "/"
weight = 5

[builtins.symbols]
after_copy = ""
history = true
name = "symbols"
placeholder = "Symbols"
switcher_only = true
typeahead = true
weight = 5

[builtins.translation]
delay = 1000
icon = "accessories-dictionary"
name = "translation"
placeholder = "Translation"
provider = "googlefree"
switcher_only = true
weight = 5

[builtins.websearch]
icon = "applications-internet"
keep_selection = true
name = "websearch"
placeholder = "Websearch"
weight = 5
[[builtins.websearch.entries]]
name = "Google"
url = "https://www.google.com/search?q=%TERM%"

[[builtins.websearch.entries]]
name = "DuckDuckGo"
switcher_only = true
url = "https://duckduckgo.com/?q=%TERM%"

[[builtins.websearch.entries]]
name = "Ecosia"
switcher_only = true
url = "https://www.ecosia.org/search?q=%TERM%"

[[builtins.websearch.entries]]
name = "Yandex"
switcher_only = true
url = "https://yandex.com/search/?text=%TERM%"

[builtins.windows]
icon = "view-restore"
name = "windows"
placeholder = "Windows"
show_icon_when_single = true
weight = 5

[builtins.xdph_picker]
hidden = true
name = "xdphpicker"
placeholder = "Screen/Window Picker"
show_sub_when_single = true
switcher_only = true
weight = 5

[events]
on_activate = ""
on_exit = ""
on_launch = ""
on_query_change = ""
on_selection = ""

[keys]
accept_typeahead = ["tab"]
close = ["esc"]
next = ["down"]
prev = ["up"]
remove_from_history = ["shift backspace"]
resume_query = ["ctrl r"]
toggle_exact_search = ["ctrl m"]
trigger_labels = "lalt"

[keys.activation_modifiers]
alternate = "alt"
keep_open = "shift"

[keys.ai]
clear_session = ["ctrl x"]
copy_last_response = ["ctrl c"]
resume_session = ["ctrl r"]
run_last_response = ["ctrl e"]

[list]
dynamic_sub = true
keyboard_scroll_style = "emacs"
max_entries = 50
placeholder = "No Results"
show_initial_entries = true
single_click = true
visibility_threshold = 20

[search]
argument_delimiter = "#"
delay = 0
placeholder = "Search..."
resume_last_query = false